### ISSUE TITLE
to many to many

### ISSUE THREAD

**Issue by abeja21** [CAMPUSCAMARAFP2021/proyecto_Angel#1]
hola @davidpestana.

Tengo un problema a la hora del to many to many, he estado leyendo informacion sobre como funcionan y lo comprendo,
La cosa es como implementarlo dentro de los controladores porque donde he estado investigando lo hacen creando a mano las variables  pero desde el controlador no se como implementarlo.
te dejo la web por si acaso: [web](https://www.bezkoder.com/mongodb-many-to-many-mongoose/)

Gracias 🍡

**Comment by davidpestana** [comment]
Realmente tienes que implementarlo asi... bastante a mano... 

se trata de hacer las inserciones de los modelos cruzados cuando te llegan directamente anidados en la peticion..

pero no tiene por que enviarse   por ejemplo un paciente con todas sus citas y doctores... va por pasos si lo ves con logica

primero... se crea un doctor

luego se crea un paciente
y luego se van creando las citas...

no se hace todo de un solo post ... me explico? ... tienes que analizar por que necesitas hacerlo todo en un solo post.
