### ISSUE TITLE
headers undefined

### ISSUE THREAD

**Issue by abeja21** [CAMPUSCAMARAFP2021/proyecto_Angel#2]
@davidpestana lo siento que como teniamos el mismo error estaba hablando por ahi.
https://github.com/CAMPUSCAMARAFP2021/proyecto_Angel/blob/main/backend/routes/brands.js

**Comment by davidpestana** [comment]
nada tranqui, es que si no me cuesta mas llegar a las cosas... 

ya veo el fallo... es un error conceptual...

este codigo representa la accion de login al que en el req.body le llegarian ( user y pass) ... ( te logeas por que aun no tienes jwt ) y como resultado obtienes un jwt...
luego este jwt es el que recibes en cada paso por el middelware...  y como es logico no hay que ponerle middelware a la accion de login...

mira bien en todolist...  de todos modos esto es backend no frontend... 

```
router.post('/login',async(req,res)=>{
    console.log(req.body)
    const brand=req.body;
    const{name,pass}=brand
    const result=await brandControllers.login(name,pass);
    const headers=new Headers();
    headers.append("authorization",result)
    return fetch("http://localhost:3000/addclothing.html", {headers})
    .then(res => res.json())
})
```

**Comment by davidpestana** [comment]
el headers se envia desde el frontend...    al llamar al backend...

el manejador que es lo que esta definido en el codigo anterior...   es como defines la recepccion de la llamada en el backend.

no haces un fetch en el backend lo haces desde el frontend para llamar al backend.

**Comment by abeja21** [comment]
vale comprendo ya como funciona no creo que me de para implementarlo pero por si lo avanzo por mi cuenta o para usarlo en el tfg  ya se como hacerlo Muchas gracias :D.
Y perdón por las horas xp

**Comment by davidpestana** [comment]
no pasa nada por las horas.... 

si te das cuenta, practicamente es "Copiar" la capa frontend de todolist ...   y cambiar los modelos de api... luego los componentes es hacer los tuyos...
